# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.19.2
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: true
odoo_test_flavor: Both
odoo_version: 16.0
org_name: Daemo00's developments
org_slug: Daemo00
rebel_module_groups: []
repo_description: Daemo00's odoo modules
repo_name: Daemo00's odoo modules
repo_slug: odoo-modules
repo_website: https://github.com/Daemo00/odoo-modules
use_pyproject_toml: true
use_ruff: true

